### ISSUE TITLE
Option to clean up the data file

### ISSUE THREAD

**Issue by gfa** [rss2email/rss2email#89] opened 2020-01-27 21:25 UTC
Hello

this is a whistlist bug reported to Debian which I'm forwarding

> My data file regularly grows to hundreds of megabytes, until I run
> ```
>  r2e reset && r2e run --no-send
> ```
> but there's a race condition in that.
>
> Wouldn't it be possible to run e.g.
> ```
 > r2e run --forget-old
> ```
> such that the data file gets rewritten with just the IDs that are
> served by the feed? Since RSS feeds usually operate like a queue,
> and older elements are unlikely to show up again, this would help
> reduce the size of the data file without the race condition.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896516

**Comment by Ekleog** [comment] 2020-09-11 19:40
This is a duplicate of https://github.com/rss2email/rss2email/issues/49

**Closed by Ekleog** 2020-09-11 19:40 UTC
Labels: is:enhancement
