### ISSUE TITLE
Verbosity too high by default?

### ISSUE THREAD

**Issue by rayvd** [rss2email/rss2email#187] opened 2021-05-30 17:31 UTC
https://github.com/rss2email/rss2email/blob/f0dc8783f12d8812f16f16ccde315fdad27854c7/rss2email/config.py#L246

By default INFO and higher is emitted to stderr making a typical crontab based configuration quite noisy (which one can, of course, override in local config file).  Prior to this commit:

https://github.com/rss2email/rss2email/commit/4708c4b6947e27298630ec81c45a8dc02240f365

The default was ERROR and higher which seems like a more sane default (or maybe WARNING), at least for cron users?

**Comment by rayvd** [comment] 2021-05-30 17:44
I guess this is why:

https://github.com/rss2email/rss2email/issues/163#issuecomment-812453616

I don't think I personally agree with this stance.  Most frequent users of command-line tools like this one will be accustomed to needing to add verbosity flags and it's actually a bit more annoying to have the verbosity higher by default since it isn't super clear how to reduce it.

However, it seems like this was an intentional UX decision so obviously my issue can be closed out.

Maybe introducing a command-line flag to reduce verbosity whose help text references editing the verbosity section of the config file would be some good middle ground.

**Comment by auouymous** [comment] 2021-06-01 07:04
See #180, and the discussion from #179.

**Comment by Ekleog** [comment] 2021-06-18 00:53
Closing as duplicate of #180, let's get to the bottom of the discussion there :)

**Closed by Ekleog** 2021-06-18 00:53 UTC
