### ISSUE TITLE
~/.local/share/rss2email.json gets corrupted

### ISSUE THREAD

**Issue by ezbik** [rss2email/rss2email#83] opened 2019-11-27 07:10 UTC
Hello, I run `r2e` in Cron, and sometimes I want to run it manually. And I believe it leads to its JSON storage corruption, when 2 processes are run at the same time. Restoring the JSON file fixes it, of course.

```
# r2e -VV run  gaf 
2019-11-27 08:00:32,635 [INFO] refreshing feed gaf (https://pathos.tanatos.org/gaf.rss -> rss+gaf@localhost)
2019-11-27 08:00:32,636 [INFO] fetch gaf (https://pathos.tanatos.org/gaf.rss -> rss+gaf@localhost)
2019-11-27 08:00:33,086 [INFO] process gaf (https://pathos.tanatos.org/gaf.rss -> rss+gaf@localhost)
2019-11-27 08:00:33,088 [WARNING] incorrectly declared encoding: document declared as us-ascii, but parsed as utf-8: gaf (https://pathos.tanatos.org/gaf.rss -> rss+gaf@localhost)

...

2019-11-27 08:00:40,924 [INFO] send message for gaf (https://pathos.tanatos.org/gaf.rss -> rss+gaf@localhost)
Traceback (most recent call last):
  File "/usr/local/bin/r2e", line 4, in <module>
    __import__('pkg_resources').run_script('rss2email==3.11', 'r2e')
  File "/opt/rss2email/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/rss2email/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/opt/rss2email/lib/python3.6/site-packages/rss2email-3.11-py3.6.egg/EGG-INFO/scripts/r2e", line 5, in <module>
  File "/opt/rss2email/lib/python3.6/site-packages/rss2email-3.11-py3.6.egg/rss2email/main.py", line 171, in run
  File "/opt/rss2email/lib/python3.6/site-packages/rss2email-3.11-py3.6.egg/rss2email/command.py", line 92, in run
  File "/opt/rss2email/lib/python3.6/site-packages/rss2email-3.11-py3.6.egg/rss2email/feeds.py", line 358, in save
  File "/opt/rss2email/lib/python3.6/site-packages/rss2email-3.11-py3.6.egg/rss2email/feeds.py", line 370, in _save_feeds
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/rss2email.json.tmp' -> '/root/.local/share/rss2email.json'
```

Then next run:

```
 # r2e -VV run  gaf 
2019-11-27 08:01:27,564 [INFO] could not load data file using JSON
2019-11-27 08:01:27,565 [INFO] try and load data file using Pickle
Traceback (most recent call last):
  File "/opt/rss2email/lib/python3.6/site-packages/rss2email-3.11-py3.6.egg/rss2email/feeds.py", line 280, in _load_feeds
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 89808 column 6 (char 6156994)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/r2e", line 4, in <module>
    __import__('pkg_resources').run_script('rss2email==3.11', 'r2e')
  File "/opt/rss2email/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/rss2email/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/opt/rss2email/lib/python3.6/site-packages/rss2email-3.11-py3.6.egg/EGG-INFO/scripts/r2e", line 5, in <module>
  File "/opt/rss2email/lib/python3.6/site-packages/rss2email-3.11-py3.6.egg/rss2email/main.py", line 170, in run
  File "/opt/rss2email/lib/python3.6/site-packages/rss2email-3.11-py3.6.egg/rss2email/feeds.py", line 249, in load
  File "/opt/rss2email/lib/python3.6/site-packages/rss2email-3.11-py3.6.egg/rss2email/feeds.py", line 283, in _load_feeds
  File "/opt/rss2email/lib/python3.6/site-packages/rss2email-3.11-py3.6.egg/rss2email/feeds.py", line 326, in _load_pickled_data
_pickle.UnpicklingError: invalid load key, '{'.

```

And then it is broken.

```
# r2e -v
rss2email 3.11
```

**Comment by Profpatsch** [comment] 2019-11-27 10:12
The current dump is just a very naïve json dump, which of course suffers from race conditions.

afaiu, earlier versions of r2e used sqlite as its database, which we should definitely return to.

**Comment by kaashif** [comment] 2020-02-01 16:07
Some of these errors, the "no such file or directory" ones are caused by a mistake in the locking when we save the data file, we copy to a temp file, modify, then rename. This is fine except the temp file we always use has the same name, so what happens is:

* process 1 starts saving
* process 2 starts saving
* process 1 is done writing to rss2email.json.tmp with its updates
* process 2 overwrites rss2email.json.tmp with updates
* process 1 moves rss2email.json.tmp to rss2email.json but this actually has process 2's updates
* process 2 can't find rss2email.json.tmp since process 1 moved it

So process 2 throws an error but actually its updates are now in the data file. Process 1 didn't throw but actually its updates were thrown away! This problem is caused because we lock correctly when reading the config but don't lock when writing.

File locking! I hope this is actually what is causing your issue.

**Comment by Ekleog** [comment] 2020-09-11 19:37
As #94 landed, hopefully this is resolved, so I'll close :) feel free to reopen if I was wrong!

**Closed by Ekleog** 2020-09-11 19:37 UTC
Labels: is:bug
